src/Feature/PageContent/code/Controllers/DocumentCenterController.cs
using BHSearch.Components;
using BHSearch.Helpers;
using BHSearch.Models;
using BPP93Helix.Feature.PageContent.Models;
using Sitecore.Data;
using Sitecore.Data.Fields;
using Sitecore.Data.Items;
using Sitecore.Resources.Media;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Web;
using System.Web.Mvc;


namespace BPP93Helix.Feature.PageContent.Controllers
{
    public class DocumentCenterController : Controller
    {
        // GET: DocumentCenter
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult DocumentQuery(SolrQuery obj)
        {
            try
            {
                // Execute Search
                ExecuteSearch search = new ExecuteSearch();
               // obj.Handler = "/bpp_physician_index/document";
                obj.Handler = "/bpp_documentcenter_index/document";
                obj.Facets = new List<string>(new string[] {
                    "__semantics"
                 });
                if (obj.Sort == null || string.IsNullOrEmpty(obj.Sort))
                    obj.Sort = "__created_tdt";
                if (obj.SortOrder == null || string.IsNullOrEmpty(obj.SortOrder))
                    obj.SortOrder = "desc";

                SolrResponse response = search.Execute(obj);

                // Map Results to Physician Model
                List<Document> Documents = new List<Document>();
                PropertyInfo[] properties = typeof(Document).GetProperties();

                foreach (Dictionary<string, object> doc in response.Results)
                {
                    Document document = new Document();

                    foreach (PropertyInfo prop in properties)
                    {
                        object value = "";
                        if (doc.TryGetValue(prop.Name, out value))
                        {
                            // change thumbnail size, can handle from front end as well
                            if (prop.Name.Equals("Thumbnail"))
                            {
                                prop.SetValue(document, value.ToString().Replace("16", "50"));
                            }
                            else if (prop.Name.ToLower().Equals("extension"))
                            {
                                switch (value.ToString().ToLower())
                                {
                                    case "pdf":
                                        {
                                            prop.SetValue(document, "pdf.png");
                                            break;
                                        }
                                    case "doc":
                                    case "docx":
                                        {
                                            prop.SetValue(document, "word.png");
                                            break;
                                        }
                                    case "xls":
                                    case "xlsx":
                                        {
                                            prop.SetValue(document, "excel.png");
                                            break;
                                        }
                                    case "rtf":
                                        {
                                            prop.SetValue(document, "rtf-icon.png");
                                            break;
                                        }
                                    case "txt":
                                        {
                                            prop.SetValue(document, "txt-icon.png");
                                            break;
                                        }
                                    case "pptx":
                                        {
                                            prop.SetValue(document, "pptx-icon.png");
                                            break;
                                        }
                                    default:
                                        {
                                            prop.SetValue(document, "alternatedoc.png");
                                            break;
                                        }
                                }
                            }
                            else
                            {
                                prop.SetValue(document, value);
                            }
                        }
                        else
                        {
                            prop.SetValue(document, null);
                        }
                    }
                    Documents.Add(document);
                }

                // Map Views to Response
                JsonResponse json = new JsonResponse();

                // etc
                json.TotalHits = response.TotalHits;
                json.OriginalQuery = response.OriginalQuery;

                //results
                json.Results = ViewHelper.RenderViewToString(this.ControllerContext, "_SearchResults", new DocumentResultView()
                {
                    Start = obj.Start,
                    Documents = Documents
                });

                // facets
                RenderFacetView(response, "__semantics", json, "_FacetCheckboxes");

                return Json(json);
            }
            catch (Exception e)
            {
                return BuildJsonErrorResponse(e);
            }
        }

        [HttpPost]
        public JsonResult DocumentTypeahead(SolrQuery obj)
        {
            try
            {
                // Execute Search
                ExecuteSearch search = new ExecuteSearch();
                obj.Handler = "/bpp_documentcenter_index/documentSuggest";
                SolrResponse response = search.Execute(obj);

                // Map Results to Physician Model
                List<Document> Documents = new List<Document>();
                PropertyInfo[] properties = typeof(Document).GetProperties();

                foreach (Dictionary<string, object> doc in response.Results)
                {
                    Document document = new Document();

                    foreach (PropertyInfo prop in properties)
                    {
                        if (doc.TryGetValue(prop.Name, out object value))
                        {
                            prop.SetValue(document, value);
                        }
                        else
                        {
                            prop.SetValue(document, null);
                        }
                    }
                    Documents.Add(document);
                }

                return Json(Documents);
            }

            catch (Exception e)
            {
                return BuildJsonErrorResponse(e);
            }
        }

        [HttpPost]
        public JsonResult DocumentFacets(SolrQuery obj)
        {
            try
            {
                // Execute Search
                ExecuteSearch search = new ExecuteSearch();
                obj.Query = "*";
                obj.Rows = 1;
                obj.Handler = "/bpp_documentcenter_index/document";
                obj.Facets = new List<string>(new string[] {
                    "title_s"
                 });
                SolrResponse response = search.Execute(obj);

                return Json(RenderFacetList(response, obj));
            }
            catch (Exception e)
            {
                return BuildJsonErrorResponse(e);
            }
        }

        private void RenderFacetView(SolrResponse response, string facetField, JsonResponse json, string partial)
        {
            FacetView facetView = new FacetView();
            ICollection<KeyValuePair<string, int>> facets = new Collection<KeyValuePair<string, int>>();
            if (response.Facets.TryGetValue(facetField, out facets))
            {
                string filter = "";
                if (response.OriginalQuery.Filters.TryGetValue(facetField, out filter))
                {
                    facetView.Filter = filter.Split(',').ToList();
                }

                facetView.Facet = new KeyValuePair<string, ICollection<KeyValuePair<string, int>>>(facetField, facets);
                json.Facets.Add(facetField, ViewHelper.RenderViewToString(this.ControllerContext, partial, facetView));
            }
        }

        private Dictionary<string, ICollection<KeyValuePair<string, int>>> RenderFacetList(SolrResponse response, SolrQuery obj)
        {
            Dictionary<string, ICollection<KeyValuePair<string, int>>> Facets = new Dictionary<string, ICollection<KeyValuePair<string, int>>>();

            foreach (string facetField in obj.Facets)
            {
                ICollection<KeyValuePair<string, int>> facets = new Collection<KeyValuePair<string, int>>();
                if (response.Facets.TryGetValue(facetField, out facets))
                {
                    Facets.Add(facetField, facets);
                }
            }

            return Facets;
        }

        private JsonResult BuildJsonErrorResponse(Exception e)
        {
            Dictionary<string, object> error = new Dictionary<string, object>();
            error.Add("Status", "Error");
            // Comment Below to Hide Debugging
            // error.Add("Exception", new {
            //    Message = e.Message,
            //    Trace = e.StackTrace,
            //    InnerException = new
            //    {
            //        Message = e.InnerException.Message != null ? e.InnerException.Message : "",
            //        Trace = e.InnerException.StackTrace != null ? e.InnerException.StackTrace : ""
            //    }

src/Feature/PageContent/code/Views/DocumentCenter/Index.cshtml
@using Sitecore.Mvc

<div class="container">
    @*<h1 class="dcenter-header">@Html.Sitecore().Field("Title")</h1><br>*@
    <form id="docCenterSearchForm">
        <div class="row">
            <div class="col-md-10 col-xs-11">
                <input id="query" type="text" name="query" placeholder="Enter Search Term" class="form-control" autofocus />
            </div>
            <div class="col-md-2 col-md-push-0 col-sm-2 col-xs-3">
                <button type="submit" class="dcenter-search-btn"><span class="fa fa-search"></span></button>
            </div>
        </div>
    </form><br>
    <div class="row">
        <div class="col-md-3">
            <div class="dcenter-sort-wrap">
                <label class="dcenter-sort-label hidden-xs">
                    Show
                    <select id="option-sort" class="form-control dcenter-sort">
                        <option value="10">10</option>
                        <option value="20">20</option>
                        <option value="30">30</option>
                        <option value="40">40</option>
                        <option value="50">50</option>
                    </select>entries
                </label>
            </div>


        </div>
        <div class="col-md-6 dcenter-topsort-margin">

            <ul class="">
                <li>
                    <label>Sort By :</label>
                </li>
                <li>
                    <a href="" id="dcenter-datemodified">Date Modified</a>
                </li>
                <li>
                    <a href="" id="dcenter-datecreated">Date Created</a>
                </li>

                <li>
                    <select id="dcenter-az">
                        <option value="A-Z">A-Z</option>
                        <option value="Z-A">Z-A</option>
                    </select>
                </li>

            </ul>


        </div>
        <div class="dcenter-topsort-margin col-md-3">
            <label>Current Categories:</label>
            <span id="current-cat"></span>
        </div>
    </div>
    <div class="row visible-xs visible-sm">
        <div class="col-md-12">
            <div class="dcenter-result-filter">
                <p>
                    <a id="dcenter-filter-toggle">
                        Refine by Category
                        <i class="fa fa-chevron-up" aria-hidden="true"></i>
                    </a>
                </p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class=" col-md-12 dcenter-refine-show hidden-xs hidden-sm" id="dcenter-showing-top">Showing 0 - 0 of 0 entries</div>

        <div class="col-md-3">
            <div class="dcenter-filters-container">
                <div class="dcenter-filters-header hidden-xs hidden-sm">Refine by Category</div>
                <div id="type" class="dcenter-filters">


                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="dcenter-results-container">
                <ul id="results" class="dcenter-results"></ul>
            </div>
            <div class="dcenter-controls-container row">

                <div class="col-md-6 dcenter-bottom-showing" id="dcenter-showing-bottom">Showing 0 - 0 of 0 entries</div>
                <div id="pagination" class="col-md-6"></div>

            </div>

        </div>
    </div>
</div>

<script type="text/javascript" src="~/Scripts/DocumentCenter.js"></script>

src/Feature/PageContent/code/Views/DocumentCenter/_FacetCheckboxes.cshtml
@using Sitecore.Data;
@using Sitecore.Data.Items;
@model BHSearch.Models.FacetView

@if (Model != null)
{
    <div class="radio">
        <label>
            <input class="dcenter-listradio" name="docCat" id="r1" type="radio" value="" @if ((Model.Filter == null) || ((Model.Filter.Count == 1) && (Model.Filter[0].Equals("")))) { <text> checked</text> } />All
        </label>
    </div>
    foreach (KeyValuePair<string, int>
                        item in Model.Facet.Value)
    {
        ID tagID = new Sitecore.Data.ID(item.Key);
        Item tagItem = Sitecore.Context.Database.GetItem(tagID);
        @*<input type="radio" name="@Model.Facet.Key" value="@item.Key" @if (Model.Filter.Contains(@item.Key)) { <text> checked</text> }>@item.Key <text>-</text> @item.Value<br/>*@

        <div class="radio">
            <label>
                @*<input type="radio" name="@Model.Facet.Key" value="@tagItem.Name" @if (Model.Filter.Contains(@tagItem.Name)) { <text> checked</text> }>@item.Key <text>-</text> @item.Value<br/>*@
                <input class="dcenter-listradio" name="docCat" id="r1" type="radio" value="@item.Key" @if (Model.Filter.Contains(item.Key)) { <text> checked</text> } />@tagItem.Name

            </label>
        </div>
    }
}

<script>
    $(document).ready(function () {
        var selector = ".dcenter-listradio";
        $(selector).change(function () {
            //if (this.checked) {
            //    $(selector).not(this).prop('checked', false);
            //}
            main();
        });
    });
</script>

src/Feature/PageContent/code/Views/DocumentCenter/_SearchResults.cshtml
@using Sitecore.Mvc;
@model BHSearch.Models.DocumentResultView

@if (Model != null)
{
    if (Model.Documents != null && Model.Documents.Count > 0)
    {
        var count = Model.Start + 1;

        foreach (var item in Model.Documents)
        {
            @*<hr />
                <div>@count</div>
                <div>@item.Thumbnail</div>
                <div>@(!String.IsNullOrEmpty(item.Title) ? item.Title : item.BackupTitle)</div>
                <div>@item.Created</div>
                <div>@item.Updated</div>
                <div>@item.Description</div>
                count++;*@
            <li class="dcenter-result">

                <div class="row">
                    <div class="col-xs-4 col-sm-2 col-md-2">
                        <div class="dcenter-result-image">
                            <img alt='No Image' src='@string.Format("/Images/{0}", @item.Extension)' />
                        </div>
                    </div>
                    <div class="col-xs-8 col-sm-8 col-md-8">
                        <div class="dcenter-name">
                            <a href="@Url.Action("Download", "DocumentCenter", new { FilePath = item.Path })"
                               type="submit"
                               id="runReport"
                               target="_blank"
                               class="dcenter-url">
                                @(!String.IsNullOrEmpty(item.Title) ? item.Title : item.BackupTitle)
                            </a>

                            @*<a class="dcenter-url" href='#'>
                                    @(!String.IsNullOrEmpty(item.Title) ? item.Title : item.BackupTitle)
                                </a>*@

                            @if ((DateTime.Now - @item.Created).TotalDays < 10)
                            {
                                <br class="visible-xs hidden-md hidden-lg" /><span class="dcenter-title-span2">new</span>
                            }

                        </div>
                        <p>@item.Description</p>
                        <ul class="dcenter-doc-detail">
                            <li>Date Created: <span id="dcenter-dateCreated">@item.Created</span></li>
                            <li>Date Updated: @item.Updated</li>
                            @*<li>Category:</li>
                                <span>Legal</span>*@
                        </ul>

                    </div>

                    <div class="col-xs-4 col-xs-push-4   col-sm-1 col-sm-push-0 col-md-2 col-md-push-0">
                        <a href="@Url.Action("Download", "DocumentCenter", new { FilePath = item.Path })"
                           type="submit"
                           id="runReport"
                           target="_blank"
                           class="dcenter-url">
                            <button class="dcenter-download dcenter-download-btn">
                                <i class="fa fa-download" aria-hidden="true"></i>
                            </button>
                        </a>


                    </div>
                </div>
                <hr class="dcenter-result-hr">
            </li>
        }
    }
    else
    {
        <div class="col-xs-3 hidden-xs"></div>
        <div class="col-xs-2 hidden-lg"></div>
        <div class="col-xs-9 dcenter-nodoc">No documents found</div>
    }


}
<script type="text/javascript">
    function Download() {

    }
</script>