src/Feature/PageContent/code/Models/ContactUs.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace BPP93Helix.Feature.PageContent.Models
{
    public class ContactUs
    {
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "First Name is Required")]
        public string FirstName { get; set; }
        [Display(Name="Last Name")]
        [Required(ErrorMessage = "Last Name is Required")]
        public string LastName { get; set; }
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [Display(Name="Email Address")]
        [Required(ErrorMessage = " Email is Required")]
        public string Email { get; set; }
        [Display(Name="Phone")]
        [Required(ErrorMessage = "Phone is Required")]
        public string Phone { get; set; }
        public IEnumerable<SelectListItem> RoleDD { get; set; }
        [Display(Name="Role")]
        [Required(ErrorMessage = "Role is Required")]
        public string Role { get; set; }
        public string Message { get; set; }
    }
}

src/Feature/PageContent/code/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using System.Data;
using System.DirectoryServices.AccountManagement;

namespace BPP93Helix.Feature.PageContent.Models
{
    public class Login
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        /// <summary>
        /// Checks if user with given password exists in the database
        /// </summary>
        /// <param name="_username">User name</param>
        /// <param name="_password">User password</param>
        /// <returns>True if user exist and password is correct</returns>
        public static bool IsValid(string _username, string _password)
        {
            bool isValid = false;
            using (PrincipalContext pc = new PrincipalContext(ContextType.Domain, "BH"))
            {               
                // validate the credentials
                isValid = pc.ValidateCredentials(_username, _password);
                
            }

            return isValid;
        }

        public static string[] GetADGroups(string username)
        {
            string[] output = null;

            using (var ctx = new PrincipalContext(ContextType.Domain))
            using (var user = UserPrincipal.FindByIdentity(ctx, username))
            {
                if (user != null)
                {
                    output = user.GetGroups()
                        .Select(x => x.SamAccountName)
                        .ToArray();
                }
            }

            return output;
        }
    }
}

src/Feature/PageContent/code/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using Sitecore.Configuration;
using System.Net;
using System.Web.Mvc;
using BPP93Helix.Feature.PageContent.Helper;
using BPP93Helix.Feature.PageContent.Models;
using Newtonsoft.Json;
using Sitecore.Diagnostics;

namespace BPP93Helix.Feature.PageContent.Controllers
{
    public class ContactUsController : Controller
    {
        private static readonly string spAPISendMail = Settings.GetSetting("spAPISendMail");
        private static readonly string contactUsRecipient = Settings.GetSetting("contactUsRecipient");
    // GET: ContactUs
        public ActionResult Index()
        {
            // build drop down for Role
            ContactUs _contactUs = new ContactUs();
            List<string> _roles = new List<string>();
            _roles.Add("Provider");
            _roles.Add("Health Plan");
            _roles.Add("Employer");
            _roles.Add("Patient");
            _roles.Add("Other");
            
            _contactUs.RoleDD = GetSelectListItems(_roles);
            return View(_contactUs);
        }
        private IEnumerable<SelectListItem> GetSelectListItems(IEnumerable<string> roles)
        {
            var selectList = new List<SelectListItem>();
            foreach (var role in roles)
            {
                selectList.Add(new SelectListItem
                {
                    Value = role,
                    Text = role
                });
            }
            
            return selectList;
        }
        public ActionResult SubmitContact(ContactUs _us)
        {
            Message message = new Message
            {
                Body = ""
            };
            message.Body += "Dear BPP Support Member,<br/>";
            message.Body += "<br/>A new contact us request has been submitted by <b>" + _us.FirstName + " " + _us.LastName + "</b><br/>";
            message.Body += "<br/>Below are the additional details<br/>";
            message.Body += "<br/><b>Email</b> - " + _us.Email + " <br/>";
            message.Body += "<br/><b>Phone</b> - " + _us.Phone + " <br/>";
            message.Body += "<br/><b>Role</b> - " + _us.Role + " <br/>";
            message.Body += "<br/><b>Message</b> - " + _us.Message + " <br/><br/><br/>";
            message.Body += "<i>*** This is an automatically generated email, please do not reply***</i>";
            message.Subject = "New BPP contact form submitted by " + _us.FirstName + " " + _us.LastName;
            message.Recipient = contactUsRecipient; 
            message.Sender = "no-reply@bmcjax.com";
            string jo = JsonConvert.SerializeObject(message);
            HttpWebResponse response = null;
            Log.Info("BPP93Helix.Feature.PageContent.Controllers.ContactUsController :: Contact Us -> Submitting JSON Final Copy:" + jo.ToString(), jo);
            response = API.PostDataToAPI(spAPISendMail, jo.ToString());
            if (response != null)
            {
                Log.Info("BPP93Helix.Feature.PageContent.Controllers.ContactUsController :: Contact Us -> API Response : " + response, response);
                Log.Info(" -> API Response Code: " + (int)response.StatusCode, response);
            }
            else
            {
                Log.Info("BPP93Helix.Feature.PageContent.Controllers.ContactUsController :: Contact Us", this);
            }
            return Redirect("~/Home/ContactUs/SubmitContact");
            //return View("SubmitContact");
        }
    }
}

src/Feature/PageContent/code/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BHSearch;
using BHUser.Components;
using BPP93Helix.Feature.PageContent.Models;
using System.Web.Security;
using Sitecore.Security;
using Sitecore.Security.Accounts;
using Sitecore.Security.Authentication;
using System.Net;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.DirectoryServices.AccountManagement;
using System.DirectoryServices;
using Microsoft.Owin;
using Sitecore;
using Sitecore.Abstractions;
using Sitecore.Diagnostics;
using Sitecore.Pipelines.GetSignInUrlInfo;
//using LightLDAP.ActiveDirectory;

namespace BPP93Helix.Feature.PageContent.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            if (Sitecore.Context.User.IsAuthenticated)
            {
                return Redirect("~/Home/");
            }
            else
                return View();
        }

        public ActionResult MiniLogin()
        {
            return PartialView();
        }
        public ActionResult AccountProfile()
        {
            var user = User.Identity.Name;
            PrincipalContext ctx = new PrincipalContext(ContextType.Domain,"BH");
            UserPrincipal u = UserPrincipal.FindByIdentity(ctx, user);
            string drNumb = "";
            try
            {
                if (u.GetUnderlyingObjectType() == typeof(DirectoryEntry))
                {
                    // Transition to directory entry to get other properties
                    using (var entry = (DirectoryEntry)u.GetUnderlyingObject())
                    {
                        if (entry.Properties["ExtensionAttribute4"] != null)
                            drNumb = entry.Properties["ExtensionAttribute4"].Value.ToString();
                    }
                }

            } catch (Exception) { }

            return Redirect("/sitecore/content/Search/Providers/" + drNumb.Trim());
        }
    }
}

src/Feature/PageContent/code/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sitecore;
using Sitecore.Mvc.Presentation;
using Sitecore.Data;
using Sitecore.Data.Items;
using Sitecore.Data.Fields;
using BHUser.Components;
using BHUser.Models;
using BPP93Helix.Feature.PageContent.Models;
using BPP93Helix.Feature.PageContent.Helper;
using System.Web.Script.Serialization;
using Sitecore.Links;
using Sitecore.Diagnostics;

namespace BPP93Helix.Feature.PageContent.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult header()
        {
            //Sitecore.Diagnostics.Log.Info("Shared Header : Loading Dynamic Header.", this);
            //bool isUserLoggedIn = false;
            var defaultUrlOptions = LinkManager.GetDefaultUrlBuilderOptions();
            defaultUrlOptions.EncodeNames = true;
            try
            {
                User _bppUser = BHSitecore.GetBHUser();

                BppHeader _bppHeader = new BppHeader(); // this is my header object
                _bppHeader.nav = new List<BPPNav>();    // this is my navigation object
                _bppHeader.menu = new BPPMenu();
                _bppHeader.menu.MenuItems = new List<BPPMenuItem>();

                ID navItemId = new ID("204AA71D-2CF4-4CA6-A392-ED284A7C044B");
                Item headerNavItems = Context.Database.GetItem(navItemId);

                ID menuItemId = new ID("F12FAE1D-B4B0-4794-9C3F-204D0E5B3E63");
                Item HeaderMenuItem = Context.Database.GetItem(menuItemId);  // ("/sitecore/content/Components/Header Control/Header");

                ImageField imageField = HeaderMenuItem.Fields["Logo"];
                if (imageField != null && imageField.MediaItem != null)
                {
                    MediaItem siteLogo = new MediaItem(imageField.MediaItem);
                    _bppHeader.menu.SiteLogoURL = Sitecore.StringUtil.EnsurePrefix('/', Sitecore.Resources.Media.MediaManager.GetMediaUrl(siteLogo));
                    _bppHeader.menu.SiteLogo = siteLogo.Alt;
                }
                MultilistField headerMenuList = null;

                ID navList = null;
                string strHeaderDetails = BHSitecore.headerDetails();
                headerMenuList = HeaderMenuItem.Fields[strHeaderDetails.Split('|')[0]];
                navList = new ID(strHeaderDetails.Split('|')[1]);

                #region ///Build Menu Based on Authentication
                if (headerMenuList != null)
                {
                    foreach (Item headerMenuLink in headerMenuList.GetItems())
                    {
                        LinkField unAuthLink = headerMenuLink.Fields["Link"];
                        string url = "#";
                        if (unAuthLink != null)
                        {
                            url = unAuthLink.GetFriendlyUrl();
                            url = BHSitecore.parseGeneralLink(unAuthLink);
                        }
                        ImageField unAuthLogo = headerMenuLink.Fields["Icon"];
                        MediaItem unAuthLogoPath = null;
                        if (unAuthLogo != null)
                        {
                            unAuthLogoPath = new MediaItem(unAuthLogo.MediaItem);
                        }
                        _bppHeader.menu.MenuItems.Add(new BPPMenuItem
                        {
                            MenuItemLogo = Sitecore.StringUtil.EnsurePrefix('/', Sitecore.Resources.Media.MediaManager.GetMediaUrl(unAuthLogoPath)),
                            MenuItemText = headerMenuLink.DisplayName,
                            MenuItemURL = url
                        });
                    }
                }
                #endregion

                #region ///Build Navigation Menu Based on Authorization
                Item headerNavList = Sitecore.Context.Database.GetItem(navList);
                MultilistField headerNavMulList = null;
                headerNavMulList = headerNavList.Fields["Navigation Links"];

                foreach (Item parentNavItem in headerNavMulList.GetItems())
                {
                    List<Item> childItems = null;
                    childItems = parentNavItem.GetChildren().ToList();
                    List<BPPNavLinks> _childNavItem = new List<BPPNavLinks>();
                    foreach (Item child in childItems)
                    {
                        _childNavItem.Add(new BPPNavLinks
                        {
                            NavLinkText = child.DisplayName,
                            //NavLinkURL = child.Paths.Path
                            NavLinkURL = LinkManager.GetItemUrl(child, defaultUrlOptions)
                        });
                    }
                    if (parentNavItem.ID.Guid.ToString().ToUpper().Equals("736FCC62-711A-4A2A-8D45-4C55B8A1331C"))
                        _bppHeader.nav.Add(new BPPNav
                        {
                            NavItemText = parentNavItem.DisplayName,
                            //NavItemURL = parentNavItem.Children[0].Paths.Path,
                            NavItemURL = LinkManager.GetItemUrl(parentNavItem.Children[0], defaultUrlOptions),
                            NavLinks = _childNavItem
                        });
                    else
                        _bppHeader.nav.Add(new BPPNav
                        {
                            NavItemText = parentNavItem.DisplayName,
                            //NavItemURL = parentNavItem.Paths.Path,
                            NavItemURL = LinkManager.GetItemUrl(parentNavItem, defaultUrlOptions),
                            NavLinks = _childNavItem
                        });
                }
                #endregion
                return PartialView(_bppHeader);
            }
            catch (Exception ex)
            {
                Log.Info("BPP93Helix.Feature.PageContent.Controllers.SharedController :: Shared Header Exception : " + ex.ToString(), this);
                return null;
            }
        }

        public ActionResult footer()
        {
            return PartialView();
        }

        public ActionResult breadcrumb()
        {
            //Remember to set the correct Home Item ID in the GetBreadcrumbs method definition
            var breadcrumb = BHSitecore.GetBreadcrumb(Context.Item);
            if (breadcrumb != null)
                return PartialView(breadcrumb);
            else
                return null;
        }

        public ActionResult logout()
        {
            Sitecore.Security.Authentication.AuthenticationManager.Logout();
            //System.Web.Security.FormsAuthentication.SignOut();
            return Redirect("/Home");
        }
    }
}

src/Feature/PageContent/code/Views/Shared/_Layout.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
@using BHUser;
@using BHUser.Components;

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Html.Sitecore().Field("title", new { DisableWebEdit = true })</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="CODE_LANGUAGE" content="C#" />
    <meta name="vs_defaultClientScript" content="JavaScript" />
    <meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5" />

    <link href="~/Content/bpp.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    @*<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300italic,400italic,600italic,700italic,300,600,700,800" rel="stylesheet" type="text/css" />*@

    <link href="~/Assets/Content/bootstrap.min.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">*@

    <link rel="stylesheet" href="~/Assets/Content/font-awesome.css" />
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />*@
    <script type="text/javascript" src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-ui.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>

    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">*@

    @*<script src="~/Scripts/modernizr-2.6.2.js"></script>*@
    @*@Html.Sitecore().VisitorIdentification()*@
</head>
<body>
    <div>
        <!-- This is coming from _layout -->
        @{Html.RenderAction("header", "Shared");}
    </div>

    <div>
        @RenderBody()
    </div>

    <div class="navbar navbar-inverse navbar-fixed-bottom">
        @{Html.RenderAction("footer", "Shared");}
        @*@Html.Partial("footer")*@
    </div>

    <script src="~/Scripts/header_footer.js"></script>
    <script src="~/Scripts/wffm.js"></script>
    <script src="~/Scripts/PhysicianSearch.js"></script>
    <script src="~/Scripts/jquery.twbsPagination.min.js"></script>
</body>
</html>

src/Feature/PageContent/code/Views/Shared/_bodyText.cshtml
@using Sitecore.Mvc

<div id="content-body">
    @Html.Sitecore().Field("body")
</div>

src/Feature/PageContent/code/Views/Shared/_contactus.cshtml
@using Sitecore.Mvc

<!-- Two Column Right Layout Start -->
<!-- Left Column Start -->
<div id="content-left-column" class="col-md-7">

    <div id="content-heading">
        @Html.Sitecore().Field("heading")
    </div>

    <div id="content-subheading-content">
        @Html.Sitecore().Field("subheading")
    </div>

</div>
<!-- Left Column End -->
<!-- Main Right Column Start -->
<div id="right-column" class="col-md-5">
    @Html.Sitecore().Placeholder("rightsidebar")
</div>
<!-- Main Right Column End -->
<!-- Two Column Right Layout End -->

src/Feature/PageContent/code/Views/Shared/_contentHeading.cshtml
@using Sitecore.Mvc
<div id="content-left-column">
    <div id="content-heading">
        @Html.Sitecore().Field("heading")
    </div>
    <div id="content-subheading-content">
        @Html.Sitecore().Field("subheading")
    </div>
</div>

src/Feature/PageContent/code/Views/Shared/_mainImage.cshtml
@using Sitecore.Mvc

<div id="content-image">
    @Html.Sitecore().Field("Main Image", Model.PageItem, new { @class = "img-responsive" })
</div>

src/Feature/PageContent/code/Views/Shared/header.cshtml
@using Sitecore;
@using BPP93Helix.Feature.PageContent.Models
@using Sitecore.Abstractions
@using Sitecore.Pipelines.GetSignInUrlInfo
@model BppHeader
<div class="to-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                @if (Model != null && Model.menu != null)
                {
                    <a href="/"><img src="@Model.menu.SiteLogoURL" class="img-responsive logo" /></a>
                }
                else
                {
                    <img src="~/Images/bpm logo.png" class="img-responsive logo">
                }
            </div>
            <div class="col-sm-7">
                <ul class="top-icons hidden-xs hidden-sm hidden-md">
                    @if (Model != null && Model.menu != null && Model.menu.MenuItems != null)
                    {
                      if (!Sitecore.Context.User.IsAuthenticated)
                      {
                        <li>
                          @{
                            var corePipelineManager = DependencyResolver.Current.GetService<BaseCorePipelineManager>();
                            var args = new GetSignInUrlInfoArgs("website", "/Admin/Master Lookup");
                            GetSignInUrlInfoPipeline.Run(corePipelineManager, args);
                            foreach (var signIn in args.Result)
                            {
                              using (Html.BeginForm("Index", "Home", FormMethod.Post, new {@action = signIn.Href}))
                              {
                                <button class="login-button" type="submit" id="loginButton">
                                  <figure>
                                    <img class="login-button-img" runat="server" src="/Images/icon_login.png" />
                                    <figcaption>User Login</figcaption>
                                  </figure>
                                </button>
                              }
                            }
                          }
                        </li>
                        }
                        foreach (var bppMenuItem in Model.menu.MenuItems)
                        {
                        <li>
                            <a href="@bppMenuItem.MenuItemURL">
                                <figure>
                                    <img src='@bppMenuItem.MenuItemLogo' />
                                    <figcaption>@bppMenuItem.MenuItemText</figcaption>
                                </figure>
                            </a>
                        </li>
                      } 
                    } 
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="header-nav-wrap">
    <nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="5">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12">
                    <button type="button" class="navbar-toggle" data-toggle="modal" data-target="#myModal">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
            </div>
            <div class="bpp-navbar">
                <div class="collapse navbar-collapse" id="myNavbar">
                    <div class="container">
                        <ul class="nav navbar-nav top-nav pull-right">
                            @if (Model != null && Model.nav != null)
                            {
                                foreach (var bppNav in Model.nav)
                                {
                                    <div class="dropdown">
                                        @if (@bppNav.NavItemText.Contains("Provider") || @bppNav.NavItemText.Contains("Payor") || @bppNav.NavItemText.Contains("Patient") || @bppNav.NavItemText.Contains("Health"))
                                        {
                                        <li class="dropbtn" data-title="i am a..">
                                            <a href='@bppNav.NavItemURL'>
                                                <i class="fa" aria-hidden="true"></i>
                                                @*fa-chevron-down*@
                                                @bppNav.NavItemText
                                            </a>
                                        </li>
                                        }
                                        else if (@bppNav.NavItemText.Contains("Admin") || @bppNav.NavItemText.Contains("Employer"))
                                        {
                                            <li class="dropbtn" data-title="i am an..">
                                                <a href='@bppNav.NavItemURL'>
                                                    <i class="fa" aria-hidden="true"></i>
                                                    @* fa-chevron-down*@
                                                    @bppNav.NavItemText
                                                </a>
                                            </li>
                                        }
                                        else if (@bppNav.NavItemText.Contains("About") || @bppNav.NavItemText.Contains("Citizenship Reporting"))
                                        {
                                            <li class="dropbtn">
                                                <a href='@bppNav.NavItemURL'>
                                                    <i class="fa fa-chevron-down" aria-hidden="true"></i>
                                                    @bppNav.NavItemText
                                                </a>
                                            </li>
                                        }
                                        else
                                        {
                                            <li class="dropbtn" data-title="">
                                                <a href='@bppNav.NavItemURL'>
                                                    <i class="fa" aria-hidden="true"></i>
                                                    @* fa-chevron-down *@
                                                    @bppNav.NavItemText
                                                </a>
                                            </li>
                                        }

                                        @if (bppNav.NavLinks != null && bppNav.NavLinks.Count > 0)
                                        {
                                            <div class="dropdown-content">
                                                @foreach (var bppNavLinks in bppNav.NavLinks)
                                                {
                                                    <a href='@bppNavLinks.NavLinkURL'>@bppNavLinks.NavLinkText</a>
                                                }
                                            </div>
                                        }
                                    </div>
                                }
                                if (Sitecore.Context.User.IsAuthenticated)
                                {
                                    <div class="dropdown">
                                        <li>
                                            @using (Html.BeginForm("logout", "Shared", FormMethod.Post))
                                            {
                                                <button name="logout" type="submit" value="logout" class="bpp-logoutbtn">Logout</button>
                                            }
                                        </li>
                                    </div>
                                }
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content nav-modal">
            <div class="modal-header nav-modal-head">
                <div class="row modal-icons-parent">
                    <ul class="modal-icons col-xs-12 list-style-none">
                        @if (Model != null && Model.menu != null && Model.menu.MenuItems != null)
                        {
                          <li>
                            @{
                              var corePipelineManager = DependencyResolver.Current.GetService<BaseCorePipelineManager>();
                              var args = new GetSignInUrlInfoArgs("website", "/Admin/Master Lookup");
                              GetSignInUrlInfoPipeline.Run(corePipelineManager, args);
                              foreach (var signIn in args.Result)
                              {
                                using (Html.BeginForm("Index", "Home", FormMethod.Post, new {@action = signIn.Href}))
                                {
                                  <button class="login-button" type="submit" id="loginButton">
                                    <figure>
                                      <img class="login-button-img" runat="server" src="/Images/icon_login.png" />
                                      <figcaption>User Login</figcaption>
                                    </figure>
                                  </button>
                                }
                              }
                            }
                          </li>
                            foreach (var bppMenuItem in Model.menu.MenuItems)
                            {
                                <li class='@(Sitecore.Context.User.IsAuthenticated ?"col-xs-3":"col-xs-4")'><a href='@bppMenuItem.MenuItemURL'><figure><div class="imgicon"><img src='@bppMenuItem.MenuItemLogo'></div><figcaption>@bppMenuItem.MenuItemText</figcaption></figure></a></li>
                            }
                        }
                    </ul>

                </div>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                @if (Model != null && Model.nav != null)
                {
                    foreach (var bppNav in Model.nav)
                    {
                        <label class="modal-navHeader"><a href='@bppNav.NavItemURL'>@bppNav.NavItemText</a></label>
                        if (bppNav.NavLinks != null && bppNav.NavLinks.Count > 0)
                        {
                            <div class="modal-navLinks">
                                <ul>
                                    @foreach (var bppNavLinks in bppNav.NavLinks)
                                    {
                                        <li><a href='@bppNavLinks.NavLinkURL'>@bppNavLinks.NavLinkText</a></li>

                                    }
                                </ul>
                            </div>
                        }
                    }
                    if (Sitecore.Context.User.IsAuthenticated)
                    {
                        <label class="modal-navHeader">
                            @using (Html.BeginForm("logout", "Shared", FormMethod.Post))
                            {
                                <button name="logout" type="submit" value="logout" class="bpp-logoutbtn-mbl">Logout</button>
                            }
                        </label>
                    }
                }
                <div class="modal-footer-text">
                    <p class="">
                        Baptist Physician Partners, LLC is a physician-led clinically integrated provider network in Northeast Florida. This new
                        model of care brings employed physicians, independent physicians, and the resources of Baptist Health into a clinically
                        and financially aligned partnership.
                    </p>

                    <p>Copyright 2013 baptist health</p>
                </div>
            </div>
        </div>
    </div>
</div>